version: 1.0.{build}

environment:
  cmakeBuildType: Release
  gudhiCmakeOptions: -DWITH_GUDHI_EXAMPLE=ON -DWITH_GUDHI_TEST=ON -DWITH_GUDHI_UTILITIES=ON -DWITH_GUDHI_PYTHON=ON -DWITH_GUDHI_REMOTE_TEST=ON
  # On this VM, 2 versions of python are installed. Default Python_FIND_FRAMEWORK is FIRST, which means asks frameworks first
  # LAST means consult frameworks in last resort, use the PATH first
  extraCmakeOptions: -DPython_FIND_FRAMEWORK=LAST

image: macos-sonoma
stack: python 3.9

install:
  - sh: |
      git submodule update --init
      python -m pip install --user -r ext/gudhi-deploy/build-requirements.txt
      python -m pip install --user -r ext/gudhi-deploy/test-requirements.txt
      python -m pip uninstall -y pykeops
      brew update || true
      brew install ninja graphviz doxygen boost eigen gmp mpfr tbb cgal || true

build_script:
  - sh: |
      mkdir build
      cd build
      which python
      cmake -DCMAKE_BUILD_TYPE:STRING=$(cmakeBuildType) $(extraCmakeOptions) -GNinja $(gudhiCmakeOptions) ..
      ninja
      ninja doxygen
      ctest --output-on-failure
