version: 1.0.{build}

image: macos-sonoma
stack: python 3.9

install:
  - sh: |
      git submodule update --init
      python -m pip install -r ext/gudhi-deploy/build-requirements.txt
      python -m pip install -r ext/gudhi-deploy/test-requirements.txt
      python -m pip uninstall -y pykeops
      brew update || true
      brew install ninja graphviz doxygen boost eigen gmp mpfr tbb cgal || true

build_script:
  - sh: |
      mkdir build
      cd build
      which python
      cmake -DCMAKE_BUILD_TYPE:STRING=Release -GNinja -DWITH_GUDHI_EXAMPLE=ON -DWITH_GUDHI_TEST=ON -DWITH_GUDHI_UTILITIES=ON -DWITH_GUDHI_PYTHON=ON -DWITH_GUDHI_REMOTE_TEST=ON ..
      ninja
      ninja doxygen
      ctest --output-on-failure
