FROM ubuntu:20.04

# Update and upgrade distribution
RUN apt update && \
    apt upgrade -y

# Tools necessary for installing and configuring Ubuntu
RUN apt install -y \
    apt-utils \
    locales \
    tzdata

# Timezone
RUN echo "Europe/Paris" | tee /etc/timezone && \
    ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

# Locale with UTF-8 support
RUN echo en_US.UTF-8 UTF-8 >> /etc/locale.gen && \
    locale-gen && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Update again
RUN apt update

# Required for Gudhi compilation
RUN apt install -y make \
    git \
    g++ \
    cmake \
    perl \
    libboost-all-dev \
    locales \
    python3 \
    python3-pip \
    python3-tk \
    python3-grpcio \
    libfreetype6-dev \
    pkg-config \
    curl

RUN curl -LO "https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz" \
    && tar xf eigen-3.3.9.tar.gz

ADD .github/build-requirements.txt /
ADD .github/test-requirements.txt /

RUN pip3 install -r build-requirements.txt
RUN pip3 --no-cache-dir install -r test-requirements.txt

# apt clean up
RUN apt-get autoremove && rm -rf /var/lib/apt/lists/*
