// List of GUDHI examples - Doxygen needs at least a file tag to analyse comments
// In user_version, `find . -name "*.cpp"` in example and utilities folders
/*! @file Examples
 * \section Alpha_complex_examples Alpha complex
 * @example Alpha_complex_from_off.cpp
 * @example Alpha_complex_from_points.cpp
 * \section bottleneck_examples bottleneck
 * @example bottleneck_basic_example.cpp
 * @example alpha_rips_persistence_bottleneck_distance.cpp
 * @example example_nearest_landmark_table.cpp
 * @example example_witness_complex_off.cpp
 * @example example_witness_complex_sphere.cpp
 * @example example_strong_witness_complex_off.cpp
 * @example mini_simplex_tree.cpp
 * @example graph_expansion_with_blocker.cpp
 * @example simple_simplex_tree.cpp
 * @example simplex_tree_from_cliques_of_graph.cpp
 * @example example_alpha_shapes_3_simplex_tree_from_off_file.cpp
 * @example cech_complex_cgal_mini_sphere_3d.cpp
 * @example plain_homology.cpp
 * @example persistence_from_file.cpp
 * @example rips_persistence_step_by_step.cpp
 * @example rips_persistence_via_boundary_matrix.cpp
 * @example custom_persistence_sort.cpp
 * @example persistence_from_simple_simplex_tree.cpp
 * @example rips_multifield_persistence.cpp
 * @example Skeleton_blocker_from_simplices.cpp
 * @example Skeleton_blocker_iteration.cpp
 * @example Skeleton_blocker_link.cpp
 * @example Garland_heckbert.cpp
 * @example Rips_contraction.cpp
 * @example Random_bitmap_cubical_complex.cpp
 * @example example_CGAL_3D_points_off_reader.cpp
 * @example example_vector_double_points_off_reader.cpp
 * @example example_CGAL_points_off_reader.cpp
 * @example example_one_skeleton_rips_from_distance_matrix.cpp
 * @example example_one_skeleton_rips_from_points.cpp
 * @example example_rips_complex_from_csv_distance_matrix_file.cpp
 * @example example_rips_complex_from_off_file.cpp
 * @example persistence_intervals.cpp
 * @example persistence_vectors.cpp
 * @example persistence_heat_maps.cpp
 * @example persistence_landscape_on_grid.cpp
 * @example persistence_landscape.cpp
 * @example example_basic.cpp
 * @example example_with_perturb.cpp
 * @example example_custom_distance.cpp
 * @example example_choose_n_farthest_points.cpp
 * @example example_sparsify_point_set.cpp
 * @example example_pick_n_random_points.cpp
 * @example CoordGIC.cpp
 * @example Nerve.cpp
 * @example FuncGIC.cpp
 * @example VoronoiGIC.cpp
 * @example example_spatial_searching.cpp
 * @example alpha_complex_3d_persistence.cpp
 * @example alpha_complex_persistence.cpp
 * @example Weighted_alpha_complex_3d_from_points.cpp
 * @example bottleneck_distance.cpp
 * @example weak_witness_persistence.cpp
 * @example strong_witness_persistence.cpp
 * @example cubical_complex_persistence.cpp
 * @example periodic_cubical_complex_persistence.cpp
 * @example off_file_from_shape_generator.cpp
 * @example rips_distance_matrix_persistence.cpp
 * @example rips_persistence.cpp
 * @example persistence_landscapes_on_grid/create_landscapes_on_grid.cpp
 * @example persistence_landscapes_on_grid/plot_landscapes_on_grid.cpp
 * @example persistence_landscapes_on_grid/compute_scalar_product_of_landscapes_on_grid.cpp
 * @example persistence_landscapes_on_grid/compute_distance_of_landscapes_on_grid.cpp
 * @example persistence_landscapes_on_grid/average_landscapes_on_grid.cpp
 * @example persistence_intervals/compute_birth_death_range_in_persistence_diagram.cpp
 * @example persistence_intervals/compute_number_of_dominant_intervals.cpp
 * @example persistence_intervals/plot_persistence_Betti_numbers.cpp
 * @example persistence_intervals/plot_persistence_intervals.cpp
 * @example persistence_intervals/plot_histogram_of_intervals_lengths.cpp
 * @example persistence_intervals/compute_bottleneck_distance.cpp
 * @example persistence_heat_maps/create_pssk.cpp
 * @example persistence_heat_maps/create_p_h_m_weighted_by_arctan_of_their_persistence.cpp
 * @example persistence_heat_maps/create_p_h_m_weighted_by_squared_diag_distance.cpp
 * @example persistence_heat_maps/compute_distance_of_persistence_heat_maps.cpp
 * @example persistence_heat_maps/compute_scalar_product_of_persistence_heat_maps.cpp
 * @example persistence_heat_maps/create_p_h_m_weighted_by_distance_from_diagonal.cpp
 * @example persistence_heat_maps/average_persistence_heat_maps.cpp
 * @example persistence_heat_maps/plot_persistence_heat_map.cpp
 * @example persistence_heat_maps/create_persistence_heat_maps.cpp
 * @example persistence_vectors/plot_persistence_vectors.cpp
 * @example persistence_vectors/compute_distance_of_persistence_vectors.cpp
 * @example persistence_vectors/average_persistence_vectors.cpp
 * @example persistence_vectors/create_persistence_vectors.cpp
 * @example persistence_vectors/compute_scalar_product_of_persistence_vectors.cpp
 * @example persistence_landscapes/average_landscapes.cpp
 * @example persistence_landscapes/compute_scalar_product_of_landscapes.cpp
 * @example persistence_landscapes/create_landscapes.cpp
 * @example persistence_landscapes/compute_distance_of_landscapes.cpp
 * @example persistence_landscapes/plot_landscapes.cpp
 */
 
