// List of GUDHI examples - Doxygen needs at least a file tag to analyse comments
// In user_version, `find . -name "*.cpp"` in example and utilities folders
/*! @file Examples
 * @example Alpha_complex/Alpha_complex_from_off.cpp
 * @example Alpha_complex/Alpha_complex_from_points.cpp
 * @example Bottleneck_distance/bottleneck_basic_example.cpp
 * @example Bottleneck_distance/alpha_rips_persistence_bottleneck_distance.cpp
 * @example Witness_complex/example_nearest_landmark_table.cpp
 * @example Witness_complex/example_witness_complex_off.cpp
 * @example Witness_complex/example_witness_complex_sphere.cpp
 * @example Witness_complex/example_strong_witness_complex_off.cpp
 * @example Simplex_tree/mini_simplex_tree.cpp
 * @example Simplex_tree/graph_expansion_with_blocker.cpp
 * @example Simplex_tree/simple_simplex_tree.cpp
 * @example Simplex_tree/simplex_tree_from_cliques_of_graph.cpp
 * @example Simplex_tree/example_alpha_shapes_3_simplex_tree_from_off_file.cpp
 * @example Simplex_tree/cech_complex_cgal_mini_sphere_3d.cpp
 * @example Persistent_cohomology/plain_homology.cpp
 * @example Persistent_cohomology/persistence_from_file.cpp
 * @example Persistent_cohomology/rips_persistence_step_by_step.cpp
 * @example Persistent_cohomology/rips_persistence_via_boundary_matrix.cpp
 * @example Persistent_cohomology/custom_persistence_sort.cpp
 * @example Persistent_cohomology/persistence_from_simple_simplex_tree.cpp
 * @example Persistent_cohomology/rips_multifield_persistence.cpp
 * @example Skeleton_blocker/Skeleton_blocker_from_simplices.cpp
 * @example Skeleton_blocker/Skeleton_blocker_iteration.cpp
 * @example Skeleton_blocker/Skeleton_blocker_link.cpp
 * @example Contraction/Garland_heckbert.cpp
 * @example Contraction/Rips_contraction.cpp
 * @example Bitmap_cubical_complex/Random_bitmap_cubical_complex.cpp
 * @example common/example_CGAL_3D_points_off_reader.cpp
 * @example common/example_vector_double_points_off_reader.cpp
 * @example common/example_CGAL_points_off_reader.cpp
 * @example Rips_complex/example_one_skeleton_rips_from_distance_matrix.cpp
 * @example Rips_complex/example_one_skeleton_rips_from_points.cpp
 * @example Rips_complex/example_rips_complex_from_csv_distance_matrix_file.cpp
 * @example Rips_complex/example_rips_complex_from_off_file.cpp
 * @example Persistence_representations/persistence_intervals.cpp
 * @example Persistence_representations/persistence_vectors.cpp
 * @example Persistence_representations/persistence_heat_maps.cpp
 * @example Persistence_representations/persistence_landscape_on_grid.cpp
 * @example Persistence_representations/persistence_landscape.cpp
 * @example Tangential_complex/example_basic.cpp
 * @example Tangential_complex/example_with_perturb.cpp
 * @example Subsampling/example_custom_kernel.cpp
 * @example Subsampling/example_choose_n_farthest_points.cpp
 * @example Subsampling/example_sparsify_point_set.cpp
 * @example Subsampling/example_pick_n_random_points.cpp
 * @example Nerve_GIC/CoordGIC.cpp
 * @example Nerve_GIC/Nerve.cpp
 * @example Nerve_GIC/FuncGIC.cpp
 * @example Nerve_GIC/VoronoiGIC.cpp
 * @example Spatial_searching/example_spatial_searching.cpp
 * @example Alpha_complex/alpha_complex_3d_persistence.cpp
 * @example Alpha_complex/alpha_complex_persistence.cpp
 * @example Alpha_complex/weighted_periodic_alpha_complex_3d_persistence.cpp
 * @example Alpha_complex/weighted_alpha_complex_3d_persistence.cpp
 * @example Alpha_complex/periodic_alpha_complex_3d_persistence.cpp
 * @example Alpha_complex/exact_alpha_complex_3d_persistence.cpp
 * @example Bottleneck_distance/bottleneck_distance.cpp
 * @example Witness_complex/weak_witness_persistence.cpp
 * @example Witness_complex/strong_witness_persistence.cpp
 * @example Bitmap_cubical_complex/cubical_complex_persistence.cpp
 * @example Bitmap_cubical_complex/periodic_cubical_complex_persistence.cpp
 * @example common/off_file_from_shape_generator.cpp
 * @example Rips_complex/rips_distance_matrix_persistence.cpp
 * @example Rips_complex/rips_persistence.cpp
 * @example Persistence_representations/persistence_landscapes_on_grid/create_landscapes_on_grid.cpp
 * @example Persistence_representations/persistence_landscapes_on_grid/plot_landscapes_on_grid.cpp
 * @example Persistence_representations/persistence_landscapes_on_grid/compute_scalar_product_of_landscapes_on_grid.cpp
 * @example Persistence_representations/persistence_landscapes_on_grid/compute_distance_of_landscapes_on_grid.cpp
 * @example Persistence_representations/persistence_landscapes_on_grid/average_landscapes_on_grid.cpp
 * @example Persistence_representations/persistence_intervals/compute_birth_death_range_in_persistence_diagram.cpp
 * @example Persistence_representations/persistence_intervals/compute_number_of_dominant_intervals.cpp
 * @example Persistence_representations/persistence_intervals/plot_persistence_Betti_numbers.cpp
 * @example Persistence_representations/persistence_intervals/plot_persistence_intervals.cpp
 * @example Persistence_representations/persistence_intervals/plot_histogram_of_intervals_lengths.cpp
 * @example Persistence_representations/persistence_intervals/compute_bottleneck_distance.cpp
 * @example Persistence_representations/persistence_heat_maps/create_pssk.cpp
 * @example Persistence_representations/persistence_heat_maps/create_p_h_m_weighted_by_arctan_of_their_persistence.cpp
 * @example Persistence_representations/persistence_heat_maps/create_p_h_m_weighted_by_squared_diag_distance.cpp
 * @example Persistence_representations/persistence_heat_maps/compute_distance_of_persistence_heat_maps.cpp
 * @example Persistence_representations/persistence_heat_maps/compute_scalar_product_of_persistence_heat_maps.cpp
 * @example Persistence_representations/persistence_heat_maps/create_p_h_m_weighted_by_distance_from_diagonal.cpp
 * @example Persistence_representations/persistence_heat_maps/average_persistence_heat_maps.cpp
 * @example Persistence_representations/persistence_heat_maps/plot_persistence_heat_map.cpp
 * @example Persistence_representations/persistence_heat_maps/create_persistence_heat_maps.cpp
 * @example Persistence_representations/persistence_vectors/plot_persistence_vectors.cpp
 * @example Persistence_representations/persistence_vectors/compute_distance_of_persistence_vectors.cpp
 * @example Persistence_representations/persistence_vectors/average_persistence_vectors.cpp
 * @example Persistence_representations/persistence_vectors/create_persistence_vectors.cpp
 * @example Persistence_representations/persistence_vectors/compute_scalar_product_of_persistence_vectors.cpp
 * @example Persistence_representations/persistence_landscapes/average_landscapes.cpp
 * @example Persistence_representations/persistence_landscapes/compute_scalar_product_of_landscapes.cpp
 * @example Persistence_representations/persistence_landscapes/create_landscapes.cpp
 * @example Persistence_representations/persistence_landscapes/compute_distance_of_landscapes.cpp
 * @example Persistence_representations/persistence_landscapes/plot_landscapes.cpp
 */
 
