.. table::
   :widths: 30 40 30

   +--------------------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------+
   | .. figure::                                                              | The cubical complex is an example of a structured complex useful in  | :Author: Pawel Dlotko       |
   |      ../../doc/Bitmap_cubical_complex/Cubical_complex_representation.png | computational mathematics (specially rigorous numerics) and image    |                             |
   |      :alt: Cubical complex representation                                | analysis.                                                            | :Since: GUDHI 2.0.0         |
   |      :figclass: align-center                                             |                                                                      |                             |
   |                                                                          |                                                                      | :License: MIT               |
   |                                                                          |                                                                      |                             |
   +--------------------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------+
   | * :doc:`cubical_complex_user`                                            | * :doc:`cubical_complex_ref`                                                                       |
   |                                                                          | * :doc:`periodic_cubical_complex_ref`                                                              |
   +--------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+
