.. table::
   :widths: 30 40 30

   +--------------------------------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------------+
   | .. figure::                                                              | The cubical complex represents a grid as a cell complex with | :Author: Pawel Dlotko                                       |
   |      ../../doc/Bitmap_cubical_complex/Cubical_complex_representation.png | cells of all dimensions.                                     | :Since: GUDHI 2.0.0                                         |
   |      :alt: Cubical complex representation                                |                                                              | :License: MIT                                               |
   |      :figclass: align-center                                             |                                                              |                                                             |
   +--------------------------------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------------+
   | * :doc:`cubical_complex_user`                                            | * :doc:`cubical_complex_ref`                                                                                               |
   |                                                                          | * :doc:`periodic_cubical_complex_ref`                                                                                      |
   +--------------------------------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------------+
   | .. image::                                                               | * :doc:`cubical_complex_tflow_itf_ref`                       | :requires: `TensorFlow <installation.html#tensorflow>`_     |
   |      img/tensorflow.png                                                  |                                                              |                                                             |
   |      :target: https://www.tensorflow.org                                 |                                                              |                                                             |
   |      :height: 30                                                         |                                                              |                                                             |
   +--------------------------------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------------+
   | .. image::                                                               | * :doc:`cubical_complex_sklearn_itf_ref`                     | :Requires: `Scikit-learn <installation.html#scikit-learn>`_ |
   |      img/sklearn.png                                                     |                                                              |                                                             |
   |      :target: https://scikit-learn.org                                   |                                                              |                                                             |
   |      :height: 30                                                         |                                                              |                                                             |
   +--------------------------------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------------+
