.. table::
   :widths: 30 40 30

   +-----------------------------------------------------+-------------------------------------------------------------------------+------------------------------------------------------------------------------------+
   | .. figure::                                         | Delaunay complex is a simplicial complex constructed from the finite    | :Author: Vincent Rouvreau                                                          |
   |      ../../doc/Alpha_complex/alpha_complex_doc.png  | cells of a Delaunay Triangulation. The Simplicial complex filtration    |                                                                                    |
   |      :alt: Delaunay complex representation          | values can be computed with different filtrations (Delaunay complex,    | :Since: GUDHI 2.0.0                                                                |
   |      :figclass: align-center                        | Delaunay Čech complex or Alpha complex)                                 |                                                                                    |
   |                                                     |                                                                         | :License: MIT (`GPL v3 </licensing/>`_)                                            |
   |                                                     | When the simplicial complex filtration values are computed, it has the  |                                                                                    |
   |                                                     | same persistent homology as the Čech complex, while being significantly | :Requires: `Eigen <installation.html#eigen>`_ and `CGAL <installation.html#cgal>`_ |
   |                                                     | smaller.                                                                |                                                                                    |
   +-----------------------------------------------------+-------------------------------------------------------------------------+------------------------------------------------------------------------------------+
   | * :doc:`delaunay_complex_user`                      | * :doc:`delaunay_complex_ref`                                                                                                                                |
   +-----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
   | .. image::                                          | * :doc:`delaunay_complex_sklearn_itf_ref`                                                                                                                    |
   |      img/sklearn.png                                |                                                                                                                                                              |
   |      :target: installation.html#scikit-learn        |                                                                                                                                                              |
   |      :height: 30                                    |                                                                                                                                                              |
   +-----------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
