.. table::
   :widths: 30 40 30

   +-----------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------+
   | .. figure::                                                     | Edge collapse is able to reduce any flag filtration to a smaller    | :Author: Siddharth Pritam, Marc Glisse        |
   |      ../../doc/Collapse/dominated_edge.png                      | flag filtration with the same persistence, using only the           |                                               |
   |      :figclass: align-center                                    | 1-skeleton of a simplicial complex.                                 | :Since: GUDHI 3.9.0                           |
   |                                                                 | The reduction is exact and the persistent homology of the reduced   |                                               |
   |                                                                 | sequence is identical to the persistent homology of the input       |                                               |
   |                                                                 | sequence. The resulting method is simple and extremely efficient.   |                                               |
   |                                                                 |                                                                     |                                               |
   |                                                                 | Computation of edge collapse and persistent homology of a filtered  |                                               |
   |                                                                 | flag complex via edge collapse as described in                      |                                               |
   |                                                                 | :cite:`edgecollapsearxiv`.                                          |                                               |
   |                                                                 |                                                                     |                                               |
   +-----------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------+
   |                                                                 |  * :doc:`edge_collapse`                                                                                             |
   +-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
