.. list-table::
   :widths: 30 40 30
   :header-rows: 0

   * - .. figure:: img/liedetect_sum.png
        :figclass: align-center

     - LieDetect is an algorithm for estimating the representation types of compact Lie groups from finite samples of their orbits. It is currently implemented for :math:`SO(2)`, :math:`T^d`, :math:`SO(3)`, and :math:`SU(2)`.

     - :Authors: Henrique Ennes & Raphaël Tinarrage
       :Since: GUDHI 3.13.0
       :License: MIT (`GPL v3 </licensing/>`_)
       :Requires: `Pymanopt <installation.html#Pymanopt>`_ and `Autograd <installation.html#Autograd>`_

   * - * :doc:`liedetect_user`
     - * :doc:`liedetect_orbit_fitter_ref`
       * :doc:`liedetect_orthonormalize_ref`
     -

