.. table::
   :widths: 30 40 30

   +----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------+
   | .. figure::                                                    | Mapper, Nerve and Graph Induced Complexes are cover complexes, i.e.    | :Author: Mathieu Carrière                                       |
   |      ../../doc/Nerve_GIC/gicvisu.jpg                           | simplicial complexes that provably contain topological information     |                                                                 |
   |      :alt: Graph Induced Complex of a point cloud.             | about the input data. They can be computed with a cover of the data,   | :Since: GUDHI 2.3.0                                             |
   |      :figclass: align-center                                   | that comes i.e. from the preimages of a family of hypercubes covering  |                                                                 |
   |                                                                | the image of a continuous function defined on the data.                | :License: MIT (`GPL v3 </licensing/>`_)                         |
   |                                                                |                                                                        |                                                                 |
   |                                                                |                                                                        | :Requires: `CGAL <installation.html#cgal>`_ :math:`\geq` 4.11.0 |
   |                                                                |                                                                        |                                                                 |
   |                                                                |                                                                        |                                                                 |
   +----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------------------------------------------+
   | * :doc:`nerve_gic_complex_user`                                | * :doc:`nerve_gic_complex_ref`                                                                                                           |
   +----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
