.. table::
   :widths: 30 50 20

   +-----------------------------------------------------------------+-----------------------------------------------------------------------+-----------------------------------------------+
   | .. figure::                                                     | These graphical tools comes on top of persistence results and allows  | :Author: Vincent Rouvreau                     |
   |      img/graphical_tools_representation.png                     | the user to display easily persistence barcode, diagram or density.   |                                               |
   |                                                                 |                                                                       | :Introduced in: GUDHI 2.0.0                   |
   |                                                                 | Note that these functions return the matplotlib axis, allowing        |                                               |
   |                                                                 | for further modifications (title, aspect, etc.)                       | :Copyright: MIT                               |
   |                                                                 |                                                                       |                                               |
   |                                                                 |                                                                       | :Requires: matplotlib, numpy and scipy        |
   +-----------------------------------------------------------------+-----------------------------------------------------------------------+-----------------------------------------------+
   | * :doc:`persistence_graphical_tools_user`                       | * :doc:`persistence_graphical_tools_ref`                                                                              |
   +-----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
