.. table::
   :widths: 30 40 30

   +-----------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------------------------------------+
   | .. figure::                                                     | These graphical tools comes on top of persistence results and allows  | :Author: Vincent Rouvreau, Theo Lacombe                  |
   |      img/graphical_tools_representation.png                     | the user to display easily persistence barcode, diagram or density.   |                                                          |
   |                                                                 |                                                                       | :Since: GUDHI 2.0.0                                      |
   |                                                                 | Note that these functions return the matplotlib axis, allowing        |                                                          |
   |                                                                 | for further modifications (title, aspect, etc.)                       | :License: MIT                                            |
   |                                                                 |                                                                       |                                                          |
   |                                                                 |                                                                       | :Requires: `Matplotlib <installation.html#matplotlib>`__ |
   +-----------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------------------------------------+
   | * :doc:`persistence_graphical_tools_user`                       | * :doc:`persistence_graphical_tools_ref`                                                                                         |
   +-----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+
