.. table::
   :widths: 30 40 30

   +------------------------------------------------------------------+----------------------------------------------------------------+-------------------------------------------------------------------------+
   | .. figure::                                                      | Vectorizations, distances and kernels that work on persistence | :Author: Mathieu Carrière, Martin Royer, Gard Spreemann, Wojciech Reise |
   |      img/sklearn-tda.png                                         | diagrams, compatible with scikit-learn and tensorflow.         |                                                                         |
   |                                                                  |                                                                | :Since: GUDHI 3.1.0                                                     |
   |                                                                  |                                                                |                                                                         |
   |                                                                  |                                                                | :License: MIT                                                           |
   |                                                                  |                                                                |                                                                         |
   +------------------------------------------------------------------+----------------------------------------------------------------+-------------------------------------------------------------------------+
   | .. image::                                                       | * :doc:`representations`                                       | :Requires: `Scikit-learn <installation.html#scikit-learn>`_             |
   |      img/sklearn.png                                             |                                                                |                                                                         |
   |      :target: https://scikit-learn.org                           |                                                                |                                                                         |
   |      :height: 30                                                 |                                                                |                                                                         |
   +------------------------------------------------------------------+----------------------------------------------------------------+-------------------------------------------------------------------------+
   | .. image::                                                       | * :doc:`representations_tflow_itf_ref`                         | :requires: `TensorFlow <installation.html#tensorflow>`_                 |
   |      img/tensorflow.png                                          |                                                                |                                                                         |
   |      :target: https://www.tensorflow.org                         |                                                                |                                                                         |
   |      :height: 30                                                 |                                                                |                                                                         |
   +------------------------------------------------------------------+----------------------------------------------------------------+-------------------------------------------------------------------------+
