.. table::
   :widths: 30 40 30

   +----------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------------------------------+
   | .. figure::                                                    | Rips complex is a simplicial complex constructed from a one skeleton   | :Authors: Clément Maria, Pawel Dlotko, Vincent Rouvreau, Marc Glisse |
   |      ../../doc/Rips_complex/rips_complex_representation.png    | graph.                                                                 |                                                                      |
   |      :figclass: align-center                                   |                                                                        | :Since: GUDHI 2.0.0                                                  |
   |                                                                | The filtration value of each edge is computed from a user-given        |                                                                      |
   |                                                                | distance function and is inserted until a user-given threshold         | :License: MIT                                                        |
   |                                                                | value.                                                                 |                                                                      |
   |                                                                |                                                                        |                                                                      |
   |                                                                | This complex can be built from a point cloud and a distance function,  |                                                                      |
   |                                                                | or from a distance matrix.                                             |                                                                      |
   +----------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------------------------------+
   | * :doc:`rips_complex_user`                                     | * :doc:`rips_complex_ref`                                                                                                                     |
   +----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
