.. table::
   :widths: 30 40 30

   +----------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------+
   | .. figure::                                                    | The Vietoris-Rips complex is a simplicial complex built as the         | :Authors: Clément Maria, Pawel Dlotko, Vincent Rouvreau, Marc Glisse, Yuichi Ike |
   |      ../../doc/Rips_complex/rips_complex_representation.png    | clique-complex of a proximity graph.                                   |                                                                                  |
   |      :figclass: align-center                                   |                                                                        | :Since: GUDHI 2.0.0                                                              |
   |                                                                | We also provide sparse approximations, to speed-up the computation     |                                                                                  |
   |                                                                | of persistent homology, and weighted versions, which are more robust   | :License: MIT                                                                    |
   |                                                                | to outliers.                                                           |                                                                                  |
   |                                                                |                                                                        |                                                                                  |
   +----------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------+
   | * :doc:`rips_complex_user`                                     | * :doc:`rips_complex_ref`                                                                                                                                 |
   +----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
