.. table::
   :widths: 30 40 30

   +----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------+
   | .. figure::                                                    | The simplex tree is an efficient and flexible data structure for       | :Author: Clément Maria      |
   |      ../../doc/Simplex_tree/Simplex_tree_representation.png    | representing general (filtered) simplicial complexes.                  |                             |
   |      :alt: Simplex tree representation                         |                                                                        | :Since: GUDHI 2.0.0         |
   |      :figclass: align-center                                   | The data structure is described in                                     |                             |
   |                                                                | :cite:`boissonnatmariasimplextreealgorithmica`                         | :License: MIT               |
   |                                                                |                                                                        |                             |
   +----------------------------------------------------------------+------------------------------------------------------------------------+-----------------------------+
   | * :doc:`simplex_tree_user`                                     | * :doc:`simplex_tree_ref`                                                                            |
   +----------------------------------------------------------------+------------------------------------------------------------------------------------------------------+
