.. table::
   :widths: 30 40 30

   +----------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------------+
   | .. figure::                                                    | A vine is the trajectory traced by a single point in the persistence   | :Author: Hannah Schreiber                                                          |
   |      ../../doc/Vineyard/vineyard_ex2.png                       | diagram as the filtration of a same complex changes over time. The set |                                                                                    |
   |      :figclass: align-center                                   | of those vines from all (or several) points in the persistence diagram | :Since: GUDHI 3.1x.0                                                               |
   |                                                                | form a 3D space of curves called a vineyard. Vineyards can therefore   |                                                                                    |
   |                                                                | be used as a tool to analyze more dynamic systems with fixed number of | :License: MIT                                                                      |
   |                                                                | underlying elements (for example, moving point clouds).                |                                                                                    |
   |                                                                |                                                                        |                                                                                    |
   |                                                                | The implementation is based on :cite:`vineyards` and :cite:`zigzag`.   |                                                                                    |
   +----------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------------+
   | * :doc:`vineyard_user`                                         | * :doc:`vineyard_ref`                                                                                                                                       |
   |                                                                | * :doc:`vineyard_graphical_tools_ref`                                                                                                                       |
   +----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
