.. table::
   :widths: 30 40 30

   +-----------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------------------+
   | .. figure::                                                     | The q-Wasserstein distance measures the similarity between two       | :Author: Theo Lacombe, Marc Glisse      |
   |      ../../doc/Bottleneck_distance/perturb_pd.png               | persistence diagrams using the sum of all edges lengths (instead of  |                                         |
   |      :figclass: align-center                                    | the maximum). It allows to define sophisticated objects such as      | :Since: GUDHI 3.1.0                     |
   |                                                                 | barycenters of a family of persistence diagrams.                     |                                         |
   |                                                                 |                                                                      | :License: MIT, BSD-3-Clause             |
   +-----------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------------------+
   | * :doc:`wasserstein_distance_user`                              |                                                                                                                |
   +-----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
