option(WITH_GUDHI_BENCHMARK "Activate/deactivate benchmark compilation" OFF)
option(WITH_GUDHI_EXAMPLE "Activate/deactivate examples compilation and installation" OFF)
option(WITH_GUDHI_PYTHON "Activate/deactivate python module compilation and installation" ON)
option(WITH_GUDHI_TEST "Activate/deactivate examples compilation and installation" ON)
option(WITH_GUDHI_UTILITIES "Activate/deactivate utilities compilation and installation" ON)
option(WITH_GUDHI_CPP_DOCUMENTATION_ONLY    "Build only the GUDHI C++ documentation (with doxygen)." OFF)

if (WITH_GUDHI_CPP_DOCUMENTATION_ONLY)
  set (WITH_GUDHI_BENCHMARK OFF)
  set (WITH_GUDHI_EXAMPLE OFF)
  set (WITH_GUDHI_PYTHON OFF)
  set (WITH_GUDHI_TEST OFF)
  set (WITH_GUDHI_UTILITIES OFF)
endif()