.. table::
   :widths: 30 50 20

   +--------------------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------+
   | .. figure::                                                              | The cubical complex is an example of a structured complex useful in  | :Author: Pawel Dlotko       |
   |      ../../doc/Bitmap_cubical_complex/Cubical_complex_representation.png | computational mathematics (specially rigorous numerics) and image    |                             |
   |      :alt: Cubical complex representation                                | analysis.                                                            | :Introduced in: GUDHI 2.0.0 |
   |      :figclass: align-center                                             |                                                                      |                             |
   |                                                                          |                                                                      | :Copyright: GPL v3          |
   |                                                                          |                                                                      |                             |
   +--------------------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------+
   | * :doc:`cubical_complex_user`                                            | * :doc:`cubical_complex_ref`                                                                       |
   |                                                                          | * :doc:`periodic_cubical_complex_ref`                                                              |
   +--------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------+
