.. table::
   :widths: 30 50 20

   +-----------------------------------------------------------------+-----------------------------------------------------------------------+-----------------------------------------------+
   | .. figure::                                                     | These graphical tools comes on top of persistence results and allows  | :Author: Vincent Rouvreau                     |
   |      img/graphical_tools_representation.png                     | the user to build easily persistence barcode, diagram or density.     |                                               |
   |                                                                 |                                                                       | :Introduced in: GUDHI 2.0.0                   |
   |                                                                 |                                                                       |                                               |
   |                                                                 |                                                                       | :Copyright: GPL v3                            |
   |                                                                 |                                                                       |                                               |
   |                                                                 |                                                                       | :Requires: matplotlib, numpy and scipy        |
   +-----------------------------------------------------------------+-----------------------------------------------------------------------+-----------------------------------------------+
   | * :doc:`persistence_graphical_tools_user`                       | * :doc:`persistence_graphical_tools_ref`                                                                              |
   +-----------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
