=====================================================================  ===========================  ===================================
:Author: Clément Maria, Pawel Dlotko, Vincent Rouvreau, Marc Glisse    :Introduced in: GUDHI 2.0.0          :Copyright: GPL v3
=====================================================================  ===========================  ===================================

+----------------------------------------------------------------+------------------------------------------------------------------------+
| .. figure::                                                    | Rips complex is a simplicial complex constructed from a one skeleton   |
|      ../../doc/Rips_complex/rips_complex_representation.png    | graph.                                                                 |
|      :figclass: align-center                                   |                                                                        |
|                                                                | The filtration value of each edge is computed from a user-given        |
|      Rips complex representation                               | distance function and is inserted until a user-given threshold         |
|                                                                | value.                                                                 |
|                                                                |                                                                        |
|                                                                | This complex can be built from a point cloud and a distance function,  |
|                                                                | or from a distance matrix.                                             |
+----------------------------------------------------------------+------------------------------------------------------------------------+
| :doc:`rips_complex_user`                                       | :doc:`rips_complex_ref`                                                |
+----------------------------------------------------------------+------------------------------------------------------------------------+
