.. table::
   :widths: 30 50 20

   +----------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------+
   | .. figure::                                                    | A Tangential Delaunay complex is a simplicial complex designed to      | :Author:    Clément Jamin          |
   |      ../../doc/Tangential_complex/tc_examples.png              | reconstruct a :math:`k`-dimensional manifold embedded in :math:`d`-    |                                    |
   |      :figclass: align-center                                   | dimensional Euclidean space. The input is a point sample coming from   | :Introduced in:    GUDHI 2.0.0     |
   |                                                                | an unknown manifold. The running time depends only linearly on the     |                                    |
   |                                                                | extrinsic dimension :math:`d` and exponentially on the intrinsic       | :Copyright: GPL v3                 |
   |                                                                | dimension :math:`k`.                                                   |                                    |
   |                                                                |                                                                        | :Requires: CGAL :math:`\geq` 4.8.0 |
   +----------------------------------------------------------------+------------------------------------------------------------------------+------------------------------------+
   | * :doc:`tangential_complex_user`                               | * :doc:`tangential_complex_ref`                                                                             |
   +----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
