.. table::
   :widths: 30 50 20

   +-------------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------------------------------------------------------+
   | .. figure::                                                       | Witness complex :math:`Wit(W,L)` is a simplicial complex defined on  | :Author: Siargey Kachanovich                                                |
   |      ../../doc/Witness_complex/Witness_complex_representation.png | two sets of points in :math:`\mathbb{R}^D`.                          |                                                                             |
   |      :alt: Witness complex representation                         |                                                                      | :Introduced in: GUDHI 2.0.0                                                 |
   |      :figclass: align-center                                      | The data structure is described in                                   |                                                                             |
   |                                                                   | :cite:`boissonnatmariasimplextreealgorithmica`.                      | :Copyright: GPL v3                                                          |
   |                                                                   |                                                                      |                                                                             |
   |                                                                   |                                                                      | :Requires: Eigen3 and CGAL :math:`\geq` 4.6.0 for Euclidean versions only   |
   +-------------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------------------------------------------------------+
   | :doc:`witness_complex_user`                                       | * :doc:`witness_complex_ref`                                         |                                                                             |
   |                                                                   | * :doc:`strong_witness_complex_ref`                                  |                                                                             |
   |                                                                   | * :doc:`euclidean_witness_complex_ref`                               |                                                                             |
   |                                                                   | * :doc:`euclidean_strong_witness_complex_ref`                        |                                                                             |
   +-------------------------------------------------------------------+----------------------------------------------------------------------+-----------------------------------------------------------------------------+
